spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/opteamer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

server:
  port: 8080

